hostname: "0.0.0.0"  # Listen on all interfaces by default
port: 4000

# Debug configuration (optional)
debug:
  level: "debug"  # Possible values: "error", "warn", "info", "debug", "verbose"

# Authentication configuration (optional)
# auth:
#   basic:
#     enabled: true
#     credentials:
#       - username: "admin"
#         password: "your-secure-password"
#   bearer:
#     enabled: true
#     tokens:
#       - "your-secure-token"

servers:
  # run an MCP server with npx
  filesystem:
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-filesystem"
      - "/Users/marcosanvido/src/"

  # # run a an MCP server from local source
  # puppeteer:
  #   command: tsx
  #   args:
  #     - "/Users/marcosanvido/AI/MCP-Servers/src/puppeteer/index.ts"

  # youtube:
  #   command: tsx
  #   args:
  #     - "/Users/marcosanvido/AI/mcp-server-youtube-transcript/src/index.ts"